

<div class="row" id="tittle1" style=" font-weight: normal; color: #F5F5F5">
	<h3>BASES Y CONDICIONES</h3>
</div>


<div class="row"  style="padding-top: 80px;color: #F5F5F5; letter-spacing: 1px; padding-bottom: 150px;">
	<div class="col-xs-12" >
		<h4>1.	ÁMBITO DE APLICACIÓN </h4>
		<p>1.1. Este programa denominado “Exploradores” (el “Programa”), organizado por Massalin Particulares S.R.L. ("MP"), se desarrollará en los puntos de venta de la Ciudad Autónoma de Buenos Aires que tengan relación comercial con MP y que hayan sido previamente seleccionados a exclusivo criterio de MP (los “PDV”).</p>
		<p>1.2. Para participar del Programa no se requiere la compra de producto alguno y podrán hacerlo todas las personas físicas titulares de PDV (ya sea en forma directa o quien se encuentre válidamente designado como representante legal en caso de una sociedad comercial) y hasta un máximo de 2 (dos) empleados del PDV que atendieren al público y que se encuentren en el PDV al momento de la visita del Representante (conforme este término se define en el punto 1.3), siempre que los PDV: (i) tuvieren la  correspondiente habilitación comercial; (ii) vendieren cigarrillos y productos de tabaco, exclusivamente, a consumidores finales; y (iii) respetasen cabalmente el precio de venta al público de cigarrillos y productos de tabaco vigente en la República Argentina, que MP publica en medios masivos de comunicación y/o comunica a través de sus representantes.</p>
		<p>1.3. MP se reserva el derecho exclusivo y excluyente de seleccionar los PDV que podrán participar en el Programa, sin que los no seleccionados tengan derecho a objeción y/o reclamo alguno. La selección será comunicada por MP a los titulares de los PDV seleccionados a través de un representante de MP (el “Representante”).</p>

		<h4>2. DEFINICIONES </h4>
		<p>2.1. A los efectos del presente Programa, se tendrán en cuenta las siguientes definiciones:</p>
		<ul>
			<li>“Bases”: son las estipulaciones y cláusulas establecidas en este documento y en todas las modificaciones futuras que pudieran efectuarse, que regirán el funcionamiento del Programa.</li>
			<li>“Código”: es una secuencia alfanumérica de 6 (seis) dígitos que los Participantes deberán cargar en el Sitio para sumar Kilómetros.</li>
			<li>“Kilómetros”: es la unidad de medida en la que se establecerá el puntaje que oportunamente se asigne a los Participantes del Programa, de acuerdo al sistema de puntuación que se establece en las presentes Bases. </li>
			<li>“Participante/s”: es el titular del PDV - ya sea en forma directa o quien se encuentre válidamente designado como representante legal en caso de una sociedad comercial – y hasta un máximo de 2 (dos) empleados del PDV que atendieren al público y que se encuentren en el PDV al momento de la visita del Representante; que hubieren adherido al Programa y cuya adhesión hubiere sido aceptada por MP conforme lo estipulado en los puntos 4.2 y 4.3 de estas Bases.</li>
			<li>“Potencial/es Ganador/es”: es/son el/los Participante/s que resultare/n beneficiado/s en el Programa, conforme lo dispuesto en las presentes Bases.  </li>
			<li>“Premio/s”: en conjunto el Premio Bicicleta, el Premio GirftCard y el Premio Viaje.  </li>
			<li>“Premio/s GiftCard”: consiste en la entrega de 1 (una) “Gift Card Cencosud” por un valor de $500 (pesos quinientos). Se deja constancia de que la Gift Card Cencosud: (i) será al portador; (ii) tendrá la vigencia que indicare dicha Gift Card; (iii) podrá ser canjeada en cualquier sucursal de Jumbo, Easy, Vea, Disco o Blaisten ; y (iv) estará sujeta a demás términos y condiciones que indicare la Gift Card respectiva, no teniendo MP responsabilidad alguna con respecto a sus cláusulas, canje ni a las decisiones que CENCOSUD pudiere tomar, por cualquier motivo, en relación a la Gift Card ni su utilización</li>
			<li>“Premio/s Viaje”: consiste en la entrega de 1 (un) voucher de la empresa de viajes TSS Viajes S.A. por un valor de $20.000 (pesos veinte mil). Se deja constancia de que el voucher: (i) será al portador; (ii) tendrá la vigencia que indicare dicho voucher; y (iii) estará sujeta a demás términos y condiciones que indicare TSS Viajes S.A., no teniendo MP responsabilidad alguna con respecto a las condiciones, canje ni a las decisiones que TSS Viajes S.A. pudiere tomar, por cualquier motivo, en relación al voucher ni su utilización.   </li>
			<li>“Programa”: es el Programa de incentivos y beneficios denominado “Exploradores”, sujeto a las presentes Bases.  </li>
			<li>“Sitio”: Es el sitio web www.exploradores.com.ar, de acceso restringido, y al cual los Participantes podrán acceder a fin de llevar a cabo diferentes actividades relacionadas al Programa.</li>
		</ul>	
		<h4>3. PLAZO DE VIGENCIA </h4>
		<p>3.1. Este Programa tendrá vigencia entre el 04 de abril de 2016 y el 31 de mayo de 2016, ambas fechas inclusive.</p>
		<p>3.2. MP se reserva el derecho de suspender y/o terminar el presente Programa en cualquier momento, sin causa y sin otra obligación que la de comunicar tal decisión a los Participantes a través de los medios que MP considerare convenientes, con una antelación mínima de 10 (diez) días corridos a la fecha de efectiva suspensión o terminación. El ejercicio de este derecho por parte de MP no otorgará a los Participantes derecho a reclamo y/o indemnización alguna.</p>
		<p>3.3. En el supuesto de suspensión o terminación del Programa, el Participante tendrá un plazo de 1 (un) mes contado a partir de la fecha de efectiva suspensión o terminación, para canjear sus Kilómetros acumulados, bajo apercibimiento de caducidad de los Kilómetros en caso de no ejercer su derecho en la forma y dentro del plazo establecido. </p>
		<p></p>

		<h4>4. SISTEMA DE INGRESO Y CONDICIONES DE PERMANENCIA </h4>
		<p>4.1. Independientemente de la selección previa por parte de MP, para hacer efectiva su adhesión al Programa, el titular del PDV, o cualquiera de sus empleados, deberá acceder al Sitio, ingresar el Código de registro que previamente le hubiere proporcionado el Representante y aceptar expresamente las políticas de bases de datos de MP. Asimismo, el titular del PDV, o cualquiera de sus empleados, deberán completar el Formulario de Registro, informando un número telefónico y una casilla de email de contacto y aceptando expresamente las Bases. Finalizado este proceso, quien haya completado el Formulario de Registro, recibirá un e-mail en su casilla de correo electrónico con las instrucciones para poder finalizar el proceso de registro, a partir del cual podrá acceder al Sitio utilizando su “nombre de usuario” que le será entregado por un Representante y la contraseña que hubiere creado durante el proceso de registro. </p>
		<p>4.2. Aquellos que finalicen satisfactoriamente el proceso mencionado en el apartado anterior, serán considerados “Participantes” a los efectos de este Programa y habrán creado una cuenta única donde tanto el dueño del PDV como sus empleados (en un máximo de dos empleados) podrán acumular sus Kilómetros (la “Cuenta”). Se deja expresa constancia de que existirá una sola Cuenta por PDV. </p>
		<p>4.3. Se deja expresa constancia de que la adhesión al Programa es responsabilidad exclusiva del titular de cada PDV seleccionado y su empleado, si este último hubiere realizado la registración, quienes – indefectiblemente y sin excepción – deberán completar el Formulario de Registro en el Sitio. En ningún caso, los Representantes ni MP serán los responsables del alta del PDV en el Programa ni de la carga del Formulario de Registro. </p>
		<p>4.4. La posibilidad de los Participantes de acumular Kilómetros conforme a lo estipulado en estas Bases, comenzará una vez suscripto en debida forma el Formulario de Registro y siempre que se cumplan con los demás requisitos aquí establecidos.</p>
		<p>4.5. Los titulares de los PDV, o sus empleados, podrán ingresar al Programa y participar de él mientras cumplan con los requisitos y condiciones aquí establecidos y mientras el Programa no hubiere culminado o sido suspendido o cancelado por MP. </p>
		<p>4.6. Salvo autorización expresa de MP, ningún titular de PDV, o sus empleados, podrán ingresar al Programa si se encontrare el titular del PDV en mora con MP en el cumplimiento de cualquiera de sus obligaciones contractuales, originadas en la relación comercial que el titular del PDV mantiene con MP. </p>
		<p>4.7. Asimismo, con posterioridad al ingreso del Participante en el Programa, cualquier incumplimiento del Participante de las obligaciones comerciales que mantiene con MP (incluyendo, sin que implique limitación, la inobservancia del precio de venta al público vigente en la República Argentina), dará derecho a esta última, a su exclusivo criterio, a: (i) anular la totalidad de los Kilómetros que tuviere acumulados hasta ese momento en su Cuenta el Participante; y/o (ii) suspender y/o dejar sin efecto la participación del Participante y su Cuenta en el Programa, sin derecho a reclamo alguno por parte del Participante, y sin que éste pueda requerir el canje de los Kilómetros que pudiere tener acumulados hasta ese momento. El ejercicio de cualquiera de estos derechos no requerirá de intimación previa por parte de MP, y podrá ser ejercido desde el momento en que ésta constatare el incumplimiento en cuestión. La decisión de MP será comunicada al Participante mediante correo electrónico enviado a la dirección por él provista en el Formulario de Registro. Esta decisión de MP será inapelable e irrecurrible.</p>
		<p>4.8. La participación y permanencia de los Participantes en el Programa se regirá por las presentes Bases, por sus Anexos que las integraren y toda otra comunicación que MP brindare a los Participantes. </p>
	
		<h4>5. RÉGIMEN DE FUNCIONAMIENTO DEL PROGRAMA </h4>
		<p>5.1. El Programa ofrece la posibilidad de ganar: (i) 1 (uno) de los 3 (tres) Premios Viajes disponibles; (ii) 1 (uno) de los 4 (cuatro) Premios Bicicleta disponibles; o (iii) 1 (uno) de los 73 (setenta y tres)  Premios Bicicleta disponibles. Se deja expresa constancia que cada Premio incluirá el beneficio respectivo tanto para el titular del PDV así como también para los empleados de dicho PDV que hubieren participado del Programa de acuerdo a las presentes Bases.</p>
		<p>5.2. A efectos del Programa, los Participantes serán visitados por un Representante en 1 (una) oportunidad, en el horario normal y habitual de atención de los PVD. Si el PDV se encontrare cerrado - por cualquier causa – el Representante no estará obligado a reprogramar su visita. Durante la visita, el Representante entregará al Participante: (a) una comunicación explicativa de la mecánica del Programa; (b) una comunicación con el objetivo de volumen de la marca Marlboro para los meses Abril y Mayo de 2016; y (c) 200 (doscientas) tarjetas (la/s “Tarjeta/s”) que contendrán un código alfanumérico único e irrepetible para cada PDV, compuesto de 6 (seis) dígitos, el Código. Este Código permitirá identificar a cada PDV con una única Cuenta y, en consecuencia, a sus Participantes. </p>
		<p>5.3. Para participar del Programa, los Participantes deberán sumar Kilómetros en su Cuenta, los cuales adquirirán al cumplir los siguientes desafíos: (i) conseguir que consumidores adultos de productos de tabaco– durante la vigencia del Programa - ingresen y se registren en el sitio web www.marlboro.com.ar, y carguen el Código incluido en la Tarjeta que el Participante le haya entregado previamente en el PDV– el Participante no podrá entregar más de 1 (una) Tarjeta por cada consumidor de productos  de tabaco (el “Desafío Tarjeta”); (ii) alcanzar un objetivo mensual de volumen -el cual será comunicado oportunamente por un Representante- de la marca Marlboro expresado en atados de 20 (veinte) cigarrillos de cualquier versión durante el periodo Abril-Mayo de 2016 (el “Desafío Volumen”) manteniendo su volumen regular de otras marcas de MP; e (iii) ingresar y registrarse en el Sitio y completar una actividad que estará disponible durante la vigencia del Programa (el “Desafío Actividad” y en conjunto con el Desafío Tarjeta y el Desafío Volumen, indistintamente el/los “Desafío/s”). </p>
		<p>5.4. Por cada Desafío que el PDV cumpla de forma exitosa sumará los siguientes Kilómetros en su Cuenta: (i) 100 Kilómetros por cada Código ingresado bajo los términos del Desafío Tarjeta; (ii) 300 Kilómetros por cada objetivo de volumen alcanzado bajo los términos del Desafío Volumen; y (iii) 200 Kilómetros por completar la actividad bajo los términos del Desafío Actividad.</p>
		<p>5.5. Finalizado el Programa, los 80 (ochenta)  PDV que, a las 23:59 hs. del 31 de Mayo de 2016, hubieren obtenido la mayor cantidad de Kilómetros, serán considerados como potenciales ganadores de los Premios (los “Potenciales Ganadores”) de acuerdo al siguiente detalle: los 3 (tres) PDV que hayan sumado la mayor cantidad de Kilómetros serán Potenciales Ganadores del Premio Viaje; los 4 (cuatro) PDV que, según la cantidad de Kilómetros sumados, y tengan las posiciones 4°, 5°, 6° y 7°, serán Potenciales Ganadores del Premio Bicicleta; y aquellos PDV que ocupen las posiciones desde el 8° al 80° puesto, serán Potenciales Ganadores del Premio Giftcard.</p>
		<p>5.6. En caso de producirse un empate entre 2 (dos) o más Participantes que obtuvieren la ubicación n° 80, éste se definirá a favor del Participante que primero hubiere obtenido la cantidad de Kilómetros motivo del empate. Asimismo, los Participantes que se ubicaren entre las posiciones 81 y 100 (ambas inclusive), serán considerados como potenciales ganadores suplentes (los “Potenciales Ganadores Suplentes”), que adquirirán el carácter de Potenciales Ganadores - de acuerdo al orden de sus posiciones – en caso de que cualquier Potencial Ganador no adquiriese, por cualquier razón, el derecho al Premio.</p>
		<p>5.7. Los Potenciales Ganadores serán notificados de su calidad de tales a través de un Representante en los PDV. En dicha ocasión, para convertirse en ganadores (el/los “Ganador/es”), los Potenciales Ganadores deberán suministrar al Representante su nombre, apellido y número de DNI. Dentro de los 30 (treinta) días de finalizado este proceso, los Representantes entregarán a los Ganadores el premio correspondiente. Contra la entrega de los Premios, los Ganadores deberán firmar el formulario de constancia de entrega respectivo.   </p>

		<h4>6. PREMIOS</h4>
		<p>6.1. Los Premios no incluyen ninguna otra prestación, bien o servicio no enumerado expresamente en estas Bases y no son transferibles a persona alguna ni redimibles en dinero efectivo u otros bienes o servicios. Se procurará que no queden premios sin asignar. Si de todos modos quedasen Premios no asignados, estos quedarán en poder de MP. En el supuesto que cualquiera de los Potenciales Ganadores no pudieren o no quisieren acceder a los Premios, por cualquier causa, perderán automáticamente todo derecho a la asignación del Premio y no tendrán nada que reclamar a MP por ningún concepto. </p>
		<p>6.2. MP no será responsable por ningún daño o perjuicio de ningún tipo que pudieren sufrir los Participantes, Potenciales Ganadores y/o Ganadores en sus personas o en sus bienes, con motivo de su participación en el Programa o con relación al uso de los Premios. Asimismo, MP no otorga garantía de calidad, evicción, vicios redhibitorios, funcionamiento, ni ninguna otra con relación a los Premios, debiendo dirigirse cualquier reclamo a los fabricantes, vendedores o importadores de los mismos.</p>		
		<p>6.3. Queda expresamente establecido que los Ganadores de los Premios (y sus acompañantes, en caso que existieran en el Premio Viaje) asumen cualquier riesgo, previsible o no, por cualquier accidente, daños y perjuicios y/o lesiones físicas que pudieren sufrir (incluyendo la muerte) en relación a los Premios. Asimismo, los Ganadores (y sus acompañantes, en caso que existieran en el Premio Viaje) eximen de responsabilidad y liberan de todo derecho y/o reclamo que pudieren poseer, o que pudiere originarse en adelante contra MP y/o cualquiera de sus afiliadas o controlantes, por cualquier y todos los daños y perjuicios, lesiones físicas (incluyendo la muerte) y/o reclamos que pudieren ser mantenidos por el Ganador y/o sus acompañantes y que surgieren directa o indirectamente de la ejecución y/o utilización de los Premios. En tal sentido, los Ganadores (y sus acompañantes, en caso que existieran en el Premio Viaje) acuerdan por las presentes Bases no iniciar acciones judiciales contra MP y o cualquiera de sus afiliadas o controlantes por cualquier daño y perjuicio y/o lesión física (incluyendo la muerte) que pudieren sufrir.</p>
		<p>6.4. En el supuesto que por cuestiones ajenas a MP, ésta no pudiere entregar y/o hacer efectivo los Premios descriptos en estas Bases, MP tendrá la facultad de reemplazarlo por otro de similares características o valor, sin que ello pudiere generar derecho a reclamo alguno por parte de los Participantes y/o Potencial Ganador. </p>
		<p>6.5. MP podrá ampliar la cantidad de Premios ofrecidos y/o el plazo de vigencia del Programa. Asimismo, MP podrá cancelar, suspender o modificar el Programa cuando circunstancias no previstas en estas Bases, o que constituyan caso fortuito o fuerza mayor, lo justifiquen (incluyendo – sin que la presente enumeración implique limitación – prohibiciones y/o restricciones impuestas por disposiciones legales nacionales, provinciales o municipales, que afectaren el desarrollo del presente Programa).</p>
		<p>6.6. Queda expresamente aclarado que los gastos extras y personales que efectuare el Ganador del Premio Viaje y/o su eventual acompañante (a modo ejemplificativo, y sin que implique limitación: excursiones y salidas no incluidas en el canje de su voucher del Premio Viaje, llamados telefónicos, regalos, extras del hotel, lavandería, comidas no incluidas, souvenirs, etc), serán a exclusivo cargo del Ganador y/o su eventual acompañante, no teniendo MP que responder por tales gastos. </p>
		<p>6.7. El Ganador del Premio Viaje deberá demostrar que sus eventuales acompañantes son mayores de 18 (dieciocho) años de edad acreditando tal circunstancia con la documentación correspondiente. Será exclusiva responsabilidad del Ganador y sus eventuales acompañantes contar con la documentación necesaria para viajar al destino correspondiente. Asimismo, el Ganador y los eventuales acompañantes deberán completar y presentar a MP la siguiente documentación: (a) Documento de exención de responsabilidad a favor de MP; (b) Certificado de buena salud y vacunación, otorgado y certificado por médico habilitado; y (c) cualquier otra documentación que MP eventualmente les solicite. Si el Ganador y/o sus Acompañantes no contaren o proporcionaren a MP la documentación mencionada perderán automáticamente todo derecho a la asignación del Premio Viaje y no tendrán nada que reclamar a MP por ningún concepto, pudiendo MP asignar el Premio Viaje al Potencial Ganador Suplente que correspondiere. </p>		

		<h4>7. MISCELÁNEAS</h4>
		<p>7.1. La mera participación en el presente Programa implica la autorización de los Participantes, Potenciales Ganadores y Ganadores, para que MP utilice sus nombres, voces e imágenes con fines comerciales, en los medios de comunicación y formas que MP disponga, sin que esto les otorgue derecho a la percepción de suma alguna y/o compensación de ningún tipo, durante la vigencia de la Acción y hasta los 3 (tres) años posteriores a su finalización. </p>
		<p>7.2. No podrán participar de este Programa directivos ni empleados de MP, ex empleados de MP que se hubieren desvinculado de la empresa dentro de los 30 (treinta) días anteriores a la fecha de comienzo del Programa ni personal de sus agencias de publicidad y logística involucradas en el Programa, así como tampoco sus familiares hasta el segundo grado de consanguinidad ni sus cónyuges. Tampoco podrán participar de este Programa los titulares de PDV que incumplieren con las obligaciones comerciales que mantienen con MP (incluyendo, sin que implique limitación, la inobservancia del precio de venta al público vigente en la República Argentina). Si, igualmente, uno de estos titulares de un PDV resultare Potencial Ganador, MP se reserva el derecho de no asignar el Premio. </p>
		<p>7.3. MP se reserva el derecho de admisión y participación del Programa, conservando el derecho de rechazar y/o suprimir del Programa a los Participantes que, a criterio de MP, infringieren las presentes Bases. </p>
		<p>7.4. El Sitio puede contener enlaces a otros sitios web, lo cual no indica que sean propiedad de o que sean operados por MP. En virtud que MP no tiene control alguno sobre tales sitios web, MP no será responsable por los contenidos, materiales, acciones o servicios prestados por los mismos, ni por daños, perjuicios o pérdidas ocasionadas por la utilización de los mismos, sean causadas directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relación, aprobación ni respaldo de MP a dichos sitios y sus contenidos.</p>
		<p>7.5. MP no será responsable por las fallas técnicas de ningún tipo, de hardware o de software, por pérdida o falta de disponibilidad de conexiones de red ni por transmisiones informáticas defectuosas, incompletas, tergiversadas o retrasadas que puedan limitar, suspender o impedir de cualquier forma la capacidad de los Participantes para participar en el presente Programa.	</p>
		<p>7.6. Todo impuesto nacional o provincial que deba tributarse sobre o en relación con los Premios, toda suma que deba abonarse a sociedades del estado, autoridades nacionales o provinciales con motivo de la organización del Programa y/o del ofrecimiento de los Premios y los gastos en que incurran los Ganadores con motivo de su participación en este Programa, serán a cargo de los Ganadores. En el mismo sentido, estará a cargo de los Ganadores el pago de todos los impuestos, tasas, aranceles, sellados, gastos y honorarios de profesionales y gestores y de todo otro costo o gasto que sea necesario para hacerse acreedor del Premio en cuestión.</p>
		<p>7.7. Los interesados en obtener mayor información sobre el Programa, podrán comunicarse telefónicamente al 0800-666-6596 , en días hábiles, de lunes a viernes, de 10:00 hs. a 18:00 horas.</p>
		<p>7.8. Para cualquier cuestión judicial que pudiera derivarse de la realización del Programa, los Participantes y MP se someterán a la jurisdicción de los tribunales ordinarios de la Ciudad Autónoma de Buenos Aires. </p>
		<p>7.9. La participación en el Programa implica la aceptación de estas Bases, así como de las decisiones que adopte MP, conforme a derecho, sobre cualquier cuestión no prevista en ellas.</p>

	</div>	


</div>